repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=LLVM", "-i"]
  - repo: local
    hooks:
      - id: update-shields
        name: Update Shields and Run Tests
        entry: ./scripts/pre_commit.sh
        language: script
        pass_filenames: false
        always_run: true